services:
  server:
    build:
      context: .
    ports:
      - 8080:8080

  mysqldb:
    image: mysql:8.1
    environment:
      #      - MYSQL_DATABASE=blogging
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD= ${MYSQL_ROOT_PASSWORD}
    #      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"



volumes:
  mysql-data:
    driver: local

