services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "512M"
        reservations:
          memory: "256M"


  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1G"
        reservations:
          memory: "512M"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10


volumes:
  mysql_data:
    driver: local

