version: '3.8'

services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/expense?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    networks:
      - network
    volumes:
      - ./src:/app/src
      - ./target:/app/target
      - ~/.m2:/root/.m2
    command: ./mvn spring-boot:run
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "512M"
        reservations:
          memory: "256M"

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: expense
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - network

volumes:
  mysql_data:
    driver: local

networks:
  network:
    driver: bridge
